export const DJANGO_URL = "https://c16f-200-19-186-128.ngrok-free.app/";

//https:70ac-200-19-186-128.ngrok-free.app
export const IES_CEARA = [
  "Universidade Federal do Ceará (UFC)",
  "Universidade Federal do Ceará - Campus de Quixadá (UFC)",
  "Instituto Federal de Educação, Ciência e Tecnologia do Ceará (IFCE)",
  "Instituto Federal de Educação, Ciência e Tecnologia Sertão Central (IFCE - Sertão Central)",
  "Instituto Federal de Educação, Ciência e Tecnologia do Cariri (IFCE - Cariri)",
  "Instituto Federal de Educação, Ciência e Tecnologia do Sertão Pernambucano (IF Sertão-PE) - Campus Salgueiro",
  "Universidade Estadual do Ceará (UECE)",
  "Universidade de Fortaleza (UNIFOR)",
  "Universidade Regional do Cariri (URCA)",
  "Universidade de Fortaleza (UNIFOR)",
  "Universidade de Juazeiro do Norte (UNIJUAZEIRO)",
  "Universidade Estadual Vale do Acaraú (UVA)",
  "Universidade Federal do Cariri (UFCA)",
  "Universidade Federal do Vale do São Francisco (UNIVASF) - Campus Sertão do Cariri",
  "Faculdade Christus (CHRISTUS)",
  "Faculdade 7 de Setembro (FA7)",
  "Faculdade Maurício de Nassau (UNINASSAU)",
  "Faculdade de Medicina Estácio de Juazeiro do Norte (Estácio Juazeiro)",
  "Faculdade de Tecnologia Doutor Raimundo Sá (FATENE)",
  "Faculdade de Fortaleza (FAFOR)",
  "Faculdade Lourenço Filho (FLF)",
  "Faculdade CDL (Faculdade CDL)",
  "Faculdade Farias Brito (FB)",
  "Faculdade Luciano Feijão (FLF)",
  "Faculdade Nordeste (Fanor)",
  "Outra",
];

export const UFC_COURSES = [
  "Engenharia de Computação",
  "Engenharia Elétrica",
  "Engenharia de Telecomunicações",
  "Engenharia Civil",
  "Engenharia Mecânica",
  "Engenharia de Pesca",
  "Engenharia de Energias Renováveis",
  "Engenharia de Pesca",
  "Engenharia de Produção Mecânica",
  "Engenharia de Teleinformática",
  "Engenharia Metalúrgica e de Materiais",
  "Biologia",
  "Ciências Ambientais",
  "Geologia",
  "Ecologia",
  "Medicina",
  "Odontologia",
  "Enfermagem",
  "Farmácia",
  "Nutrição",
  "Direito",
  "Psicologia",
  "Serviço Social",
  "Ciências Sociais",
  "História",
  "Geografia",
  "Filosofia",
  "Letras",
  "Biologia",
  "Ciências Econômicas",
  "Administração",
  "Ciências Contábeis",
  "Jornalismo",
  "Publicidade e Propaganda",
  "Design",
  "Música",
  "Teatro",
  "Pedagogia",
  "Educação Física",
  "Agronomia",
  "Zootecnia",
  "Engenharia de Alimentos",
  "Medicina Veterinária",
  "Sistemas de Informação",
  "Engenharia de Software",
  "Arquitetura e Urbanismo",
  "Oceanografia",
  "Artes Visuais",
  "Outro",
];
